development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: linker_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: linker_test
  pool: 5
  username: root

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: linker_production
