development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: linker_development
  pool: 5
  username: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: linker_test
  pool: 5
  username: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: linker_production
